In [2]:
import pandas as pd
import datetime
import numpy as np
import pymongo
import json


In [20]:
def stringToDate(string):
    string = string.split("/")
    if(len(string[2]) == 4):
        string[2] = string[2][2:]
    date = string[0]+"/"+ string[1]+"/20"+string[2]
    date = datetime.datetime.strptime(date, '%d/%m/%Y')
    return date

In [21]:
def hash_match(date, away, home, ver):
    date = date.split("/")
    return hash(date[0]+date[1]+date[2]+away+home+str(ver))    

In [22]:
def getLastMatchId(id_match, nb_earlier_match):
    dates = concats['Date'].apply(stringToDate)
    #homepart
    ids_HH = dates[(dates < dates[id_match]) & (concats["HomeTeam"] == concats["HomeTeam"][id_match])].index
    ids_HA = dates[(dates < dates[id_match]) & (concats["AwayTeam"] == concats["HomeTeam"][id_match])].index
    ids_home = np.array(ids_HH,ids_HA)
    if(ids_home.shape[0] < nb_earlier_match):
        return np.nan
    else:
        ids_home = ids_home[ids_home.argsort()[-nb_earlier_match:][::-1]]
    #awaypart
    
    ids_AH = dates[(dates < dates[id_match]) & (concats["HomeTeam"] == concats["AwayTeam"][id_match])].index
    ids_AA = dates[(dates < dates[id_match]) & (concats["AwayTeam"] == concats["AwayTeam"][id_match])].index
    ids_away = np.array(ids_AH,ids_AA)
    if(ids_away.shape[0] < nb_earlier_match):
        return np.nan
    else:
        ids_away = ids_away[ids_away.argsort()[-nb_earlier_match:][::-1]]
    return np.array([ids_away, ids_home])

In [23]:
concats = pd.DataFrame()
for i in range(14,20):
    concats = pd.concat([concats , pd.read_csv("data/"+str(i)+"1.csv")], sort = False,ignore_index=True)
    
for i in range(14,20):
    concats = pd.concat([concats , pd.read_csv("data/"+str(i)+"2.csv")], sort = False,ignore_index=True)

In [24]:
concats = concats[pd.notnull(concats['FTR'])]
concats = concats.drop(columns = concats.columns[22:])
concats['ID_FTR'] = concats.FTR.astype('category').cat.codes

In [25]:
hashmap = dict()

In [27]:
ids = []
for i in range(concats.shape[0]-500):
    vals = concats.iloc[i,[1,2,3]].values
    hashed = hash_match(vals[0],vals[1], vals[2], 1)
    if hashed in hashmap:
        ids.append(hashmap[hashed])
    else:
        id_match = getLastMatchId(concats.index[i],3)
        ids.append(id_match)
        hashmap[hashed] = id_match

ids

#ids = pd.Series(concats.index).apply(getLastMatchId, args=(3,))

[nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 array([[43, 25,  7],
        [35, 28,  6]], dtype=int64),
 nan,
 nan,
 array([[42, 24,  5],
        [49, 23,  4]], dtype=int64),
 nan,
 nan,
 array([[52, 30, 18],
        [44, 26,  0]], dtype=int64),
 nan,
 array([[54, 35, 28],
        [41, 21,  1]], dtype=int64),
 nan,
 array([[56, 32, 11],
        [47, 20,  2]], dtype=int64),
 array([[53, 38, 13],
        [48, 22,  3]], dtype=int64),
 array([[51, 33, 12],
        [40, 27,  8]], dtype=int64),
 array([[58, 34,  9],
        [42, 24,  5]], dtype=int64),
 array([[57, 49, 23],
        [43, 25,  7]], dtype=int64),
 array([[50, 37, 17],
        [46, 29, 19]], dtype=int64),
 array([[62, 41, 21],
        [57, 49, 23]], dtype

In [28]:
hashmap

{-4553063880936638804: nan,
 6657147974335816639: nan,
 6582331962148949036: nan,
 5477985313248485009: nan,
 6253010638887546019: nan,
 8224885923088238164: nan,
 914368607560610973: nan,
 2438434030132953777: nan,
 -8135415940656122396: nan,
 -138480804535548354: nan,
 -616788085312531256: nan,
 7200196592461709458: nan,
 8349464890805910738: nan,
 -2361902795173671100: nan,
 -2582873181223619118: nan,
 7431284489131041841: nan,
 -9114850256118427586: nan,
 -4059810628583990344: nan,
 6797419880992346244: nan,
 -3115094944039301425: nan,
 -993548224880488886: nan,
 2949870970983342423: nan,
 -4743847505686223622: nan,
 -2350055669255524324: nan,
 3491527278199584291: nan,
 -6036000063373802141: nan,
 8583164046284110144: nan,
 -3777106753313849751: nan,
 2253620933889392563: nan,
 5798987600920106123: nan,
 5361468113197534771: nan,
 3318773160554193767: nan,
 7840290202523390597: nan,
 1741808225375774651: nan,
 766430920879034186: nan,
 3855198750294015889: nan,
 -15138605281161038

In [200]:
ids = pd.DataFrame(ids)
ids = ids.reindex(concats.index)
ids = ids.dropna()

In [201]:
concats = concats.fillna(0.0)

In [202]:


concats['AAG'] = np.nan
concats['AAS'] = np.nan
concats['AASO'] = np.nan
concats['AAF'] = np.nan
concats['AAC'] = np.nan
concats['AAY'] = np.nan
concats['AAR'] = np.nan

concats['HAG'] = np.nan
concats['HAS'] = np.nan
concats['HASO'] = np.nan
concats['HAF'] = np.nan
concats['HAC'] = np.nan
concats['HAY'] = np.nan
concats['HAR'] = np.nan

for i in ids.index:
    #awaypart
    ids_away = ids[0][i][0]
    avg_goals = 0
    avg_shots = 0
    avg_shots_on = 0
    avg_fouls = 0
    avg_corners = 0
    avg_yellow = 0
    avg_red = 0
    for k in ids_away:
        if(concats.loc[i,"AwayTeam"] == concats.loc[k,"AwayTeam"]):
            avg_goals += concats.loc[k,"FTAG"]
            avg_shots += concats.loc[k,"AS"]
            avg_shots_on += concats.loc[k,"AST"]
            avg_fouls += concats.loc[k,"AF"]
            avg_corners = concats.loc[k,"AC"]
            avg_yellow += concats.loc[k,"AY"]
            avg_red += concats.loc[k,"AR"]
        else:
            avg_goals += concats.loc[k,"FTHG"]
            avg_shots += concats.loc[k,"HS"]
            avg_shots_on += concats.loc[k,"HST"]
            avg_fouls += concats.loc[k,"HF"]
            avg_corners = concats.loc[k,"HC"]
            avg_yellow += concats.loc[k,"HY"]
            avg_red += concats.loc[k,"HR"]
            
    concats.loc[i,'AAG'] = avg_goals
    concats.loc[i,'AAS'] = avg_shots
    concats.loc[i,'AASO'] = avg_shots_on
    concats.loc[i,'AAF'] = avg_fouls
    concats.loc[i,'AAC'] = avg_corners
    concats.loc[i,'AAY'] = avg_yellow
    concats.loc[i,'AAR'] = avg_red

            
    ids_home = ids[0][i][1]
    avg_goals = 0
    avg_shots = 0
    avg_shots_on = 0
    avg_fouls = 0
    avg_corners = 0
    avg_yellow = 0
    avg_red = 0
    for k in ids_home:
        if(concats.loc[i,"HomeTeam"] == concats.loc[k,"AwayTeam"]):
            avg_goals += concats.loc[k,"FTAG"]
            avg_shots += concats.loc[k,"AS"]
            avg_shots_on += concats.loc[k,"AST"]
            avg_fouls += concats.loc[k,"AF"]
            avg_corners = concats.loc[k,"AC"]
            avg_yellow += concats.loc[k,"AY"]
            avg_red += concats.loc[k,"AR"]
        else:
            avg_goals += concats.loc[k,"FTHG"]
            avg_shots += concats.loc[k,"HS"]
            avg_shots_on += concats.loc[k,"HST"]
            avg_fouls += concats.loc[k,"HF"]
            avg_corners = concats.loc[k,"HC"]
            avg_yellow += concats.loc[k,"HY"]
            avg_red += concats.loc[k,"HR"]
        
       
    
    concats.loc[i,'HAG'] = avg_goals
    concats.loc[i,'HAS'] = avg_shots
    concats.loc[i,'HASO'] = avg_shots_on
    concats.loc[i,'HAF'] = avg_fouls
    concats.loc[i,'HAC'] = avg_corners
    concats.loc[i,'HAY'] = avg_yellow
    concats.loc[i,'HAR'] = avg_red

In [203]:
concats = concats.drop([x for x in concats.index.values if x not in ids.index.values])

In [204]:
concats = concats.drop(columns = concats.columns[4:6])
concats = concats.drop(columns = concats.columns[5:20])

In [205]:
normalized_df=(concats[concats.columns[6:]]-concats[concats.columns[6:]].mean())/concats[concats.columns[6:]].std()

In [206]:
concats[concats.columns[6:]] = normalized_df

In [207]:
concats.columns[6:13]

Index(['AAG', 'AAS', 'AASO', 'AAF', 'AAC', 'AAY', 'AAR'], dtype='object')

In [208]:
concats.columns[13:]

Index(['HAG', 'HAS', 'HASO', 'HAF', 'HAC', 'HAY', 'HAR'], dtype='object')

In [209]:
ids_team = list()
names = concats["HomeTeam"].drop_duplicates()
for i in names:
    df = np.array(concats[concats["HomeTeam"] == i].index, concats[concats["AwayTeam"] == i].index)
    ids_team.append(max(df))

values = list()
for i in range(len(names)):
    if(concats.loc[ids_team[i], "HomeTeam"] == names.iloc[i]):
        values.append(concats.loc[ids_team[i], concats.columns[13:]].values.astype(float))
    else:
        values.append(concats.loc[ids_team[i], concats.columns[6:13]].values.astype(float))
        
team_data = pd.DataFrame(values)
team_data["TeamName"] =  names.values

In [215]:
concats["ID_FTR"].value_counts()

2    1747
0    1123
1    1087
Name: ID_FTR, dtype: int64

In [211]:
team_data.to_csv("teamfeatures.csv")

In [212]:
concats.to_csv("parsed_train_data.csv")

In [15]:
def pandas_to_mongo(df):
    client = pymongo.MongoClient("mongodb://plp_mongodb:27017")
    db = client['refined-database']
    df.to_json('yourjson.json',orient = "index")                               # saving to json file
    jdf = open('yourjson.json').read()                        # loading the json file 
    data = json.loads(jdf)   
    posts = db.posts
    entry_list = list()
    for i in data.keys():
        entry_list.append(data[i])
    return posts.insert_many(entry_list)
    

In [193]:
pandas_to_mongo(team_data)
pandas_to_mongo(concats)

ServerSelectionTimeoutError: plp_mongodb:27017: [Errno 11001] getaddrinfo failed